stars: Explicitly cast RAND_MAX to float
Some platforms warn about a loss of precision without an explicit cast.
We don't care too much about precision, so we can explicitly cast to
avoid the warning.

    stars.c:59:38: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]
        const float t = ((float)rand() / RAND_MAX) * (2.0f * M_PI);
                                       ~ ^~~~~~~~
    /opt/homebrew/Cellar/emscripten/2.0.15/libexec/cache/sysroot/include/stdlib.h:82:19: note: expanded from macro 'RAND_MAX'
    #define RAND_MAX (0x7fffffff)
                      ^~~~~~~~~~
    stars.c:60:48: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]
        const float r = r_range * ((float)rand() / RAND_MAX);
                                                 ~ ^~~~~~~~
    /opt/homebrew/Cellar/emscripten/2.0.15/libexec/cache/sysroot/include/stdlib.h:82:19: note: expanded from macro 'RAND_MAX'
    #define RAND_MAX (0x7fffffff)
                      ^~~~~~~~~~
    stars.c:67:52: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]
        star->initial_color = (1.0f - ((float)rand() / RAND_MAX) * 0.75f) * 255.0f;
                                                     ~ ^~~~~~~~
    /opt/homebrew/Cellar/emscripten/2.0.15/libexec/cache/sysroot/include/stdlib.h:82:19: note: expanded from macro 'RAND_MAX'
    #define RAND_MAX (0x7fffffff)
                      ^~~~~~~~~~
    3 errors generated.